FROM ubuntu:focal 

RUN apt-get update && apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  perl

# kubectl
RUN curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && apt-get install -y kubectl && apt-get clean


# Carvel tools
RUN curl -fsSL https://carvel.dev/install.sh | bash 

# Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Clean up
RUN apt-get remove -y perl
