---
resources:
  # Use the example docker configuration in the Tailscale source
- name: toolkit-source
  type: git
  icon: github
  source:
    uri: ((toolkit.repository))
    branch: ((toolkit.branch))

# Where we will push the image
- name: toolkit-image
  type: registry-image
  icon: docker
  source:
    # You need to provide these variables when
    # setting the pipeline
    repository: ((registry.fqdn))/((image.repository))
    username: ((registry.robot))
    password: ((registry.token))

jobs:
- name: create-image
  plan:
  - get: toolkit-source
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          repository: concourse/oci-build-task
      inputs:
      - name: toolkit-source
      outputs:
      - name: image
      params:
        DOCKERFILE: toolkit-source/src/container/Containerfile
      run:
        path: build
  - put: toolkit-image
    params:
      image: image/image.tar
